apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-{{ include "simpleaccounts.fullname" . }}
type: Opaque
data:
  username: {{ .Values.dbSecrets.username }}
  password: {{ .Values.dbSecrets.password }}
  dbhost: {{ .Values.dbSecrets.dbhost }}
  database: {{ .Values.dbSecrets.database }}