apiVersion: v1
kind: Service
metadata:
  name: {{ include "simpleaccounts.fullname" . }}
  labels:
    {{- include "simpleaccounts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http-tomcat
  selector:
    {{- include "simpleaccounts.selectorLabels" . | nindent 4 }}
